baseURL = 'https://sdthaker.github.io/sohamwhocodes/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-relearn'

[params]
    themeVariant = 'relearn-light'

[outputs]
    home = ['html', 'rss', 'search']